# Generated by Django 6.0.3 on 2026-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_repair_student_department_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parentnotification',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
