# Generated by Django 6.0.3 on 2026-05-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_repair_rector_model_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='enrollment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
